# Generated by Django 4.1.4 on 2022-12-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WeatherApp", "0007_alter_city_options_alter_city_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=10)),
                ("phonenumber", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "authentication",
            },
        ),
    ]
